"""Node 6: Mitigation Narrative Builder — LLM-driven drafting from fact sheet.

Uses LLM to draft a mitigation narrative grounded in the structured fact sheet.
"""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from src.services.llm_service import call_llm

from ..models.outputs import MitigationNarrative, NodeAuditRecord
from ..models.state import SentencingGraphState

logger = logging.getLogger(__name__)

PROMPT_PATH = Path(__file__).parent.parent / "prompts" / "mitigation_narrative.txt"


def _build_narrative_prompt(state: SentencingGraphState) -> tuple[str, str]:
    """Build the system and user prompts for mitigation narrative drafting."""
    system_prompt = PROMPT_PATH.read_text()

    input_data = state["input"]
    fact_sheet = state.get("mitigation_fact_sheet")

    user_prompt = f"""
OFFENSE CONTEXT:
- Statute: {input_data.offense_details.statute}
- Description: {input_data.offense_details.charge_description}
- County: {input_data.jurisdiction_context.county}

MITIGATION FACT SHEET:
{json.dumps(fact_sheet, default=str, indent=2) if fact_sheet else "No facts available — narrative cannot be drafted."}

Draft the mitigation narrative based ONLY on the facts provided above. Return JSON only."""

    return system_prompt, user_prompt


def _parse_narrative_response(raw: dict[str, Any]) -> MitigationNarrative:
    """Parse LLM response into MitigationNarrative."""
    return MitigationNarrative(
        summary=raw.get("summary", ""),
        full_narrative=raw.get("full_narrative", ""),
        key_themes=raw.get("key_themes", []),
        supporting_facts=raw.get("supporting_facts", []),
        paragraph_fact_map=raw.get("paragraph_fact_map", []),
        unsupported_claim_warnings=raw.get("unsupported_claim_warnings", []),
        tone_notes=raw.get("tone_notes", ""),
    )


def _fallback_narrative(state: SentencingGraphState) -> MitigationNarrative:
    """Generate a minimal fallback narrative without LLM."""
    fact_sheet = state.get("mitigation_fact_sheet")
    facts = fact_sheet.get("facts", []) if fact_sheet else []
    themes = fact_sheet.get("themes", []) if fact_sheet else []

    fact_texts = [f.get("text", "") for f in facts if f.get("text")]
    summary = "Mitigation narrative could not be generated by LLM. Key facts are listed below for attorney drafting."
    full_narrative = (
        "The following mitigating factors have been identified from the case record:\n\n"
        + "\n".join(f"- {t}" for t in fact_texts)
        + "\n\n[ATTORNEY: Please draft the full mitigation narrative based on these facts.]"
    )

    return MitigationNarrative(
        summary=summary,
        full_narrative=full_narrative,
        key_themes=themes,
        supporting_facts=[
            {"fact_id": f.get("fact_id", ""), "text": f.get("text", "")} for f in facts
        ],
        paragraph_fact_map=[],
        unsupported_claim_warnings=["Narrative generated as fallback — full LLM drafting failed"],
        tone_notes="Fallback narrative — attorney should draft complete narrative",
    )


async def mitigation_narrative_builder(state: SentencingGraphState) -> SentencingGraphState:
    """Mitigation narrative builder node — drafts narrative from fact sheet."""
    started_at = datetime.now(timezone.utc).isoformat()
    audit_records: list[NodeAuditRecord] = list(state.get("audit_records") or [])
    warnings: list[str] = list(state.get("warnings") or [])

    if state.get("scope_status") != "in_scope":
        audit_records.append(
            NodeAuditRecord(
                node_name="mitigation_narrative_builder",
                status="skipped",
                started_at=started_at,
                completed_at=datetime.now(timezone.utc).isoformat(),
                warnings=["Skipped: case is not in scope"],
                output_keys=[],
            )
        )
        state["audit_records"] = audit_records
        return state

    fact_sheet = state.get("mitigation_fact_sheet")
    if not fact_sheet or fact_sheet.get("fact_count", 0) == 0:
        warnings.append("No mitigation facts available — narrative will be minimal")
        state["mitigation_narrative"] = _fallback_narrative(state)
        state["warnings"] = warnings
        audit_records.append(
            NodeAuditRecord(
                node_name="mitigation_narrative_builder",
                status="warning",
                started_at=started_at,
                completed_at=datetime.now(timezone.utc).isoformat(),
                warnings=["No mitigation facts available"],
                output_keys=["mitigation_narrative"],
            )
        )
        state["audit_records"] = audit_records
        return state

    try:
        system_prompt, user_prompt = _build_narrative_prompt(state)
        raw = await call_llm(user_prompt, system=system_prompt, max_tokens=4096)
        narrative = _parse_narrative_response(raw)

        if not narrative.full_narrative:
            warnings.append("LLM returned empty narrative — using fallback")
            narrative = _fallback_narrative(state)

    except Exception as e:
        logger.warning("Mitigation narrative LLM call failed: %s — using fallback", e)
        warnings.append(f"Narrative LLM call failed: {e} — using fallback narrative")
        narrative = _fallback_narrative(state)

    state["mitigation_narrative"] = narrative
    state["warnings"] = warnings
    audit_records.append(
        NodeAuditRecord(
            node_name="mitigation_narrative_builder",
            status="ok" if not narrative.unsupported_claim_warnings else "warning",
            started_at=started_at,
            completed_at=datetime.now(timezone.utc).isoformat(),
            warnings=warnings,
            output_keys=["mitigation_narrative"],
        )
    )
    state["audit_records"] = audit_records
    return state
